/* Reset schema HoneyBee Trace Oracle. Chỉ chạy trong schema test HONEYBEE_WEB. */
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_PUBLIC_TRACE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables WHERE table_name IN (
      'QR_SECURITY_ALERTS','AUDIT_LOGS','QR_SCAN_LOGS','QR_CODES','PRODUCT_UPDATES','BATCH_STATUS_HISTORY',
      'DISTRIBUTION_HISTORY','CERTIFICATES','TRANSPORT_HISTORY','PRODUCT_ORIGIN','PRODUCTS','USERS','TRANSPORTERS','STORES','FARMS','STATUS_TRANSITIONS','APP_SCHEMA_INFO'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRODUCTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_QR_RISK_LEVEL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LOG_QR_SCAN';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRINT_OPEN_QR_ALERTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/
