SET SERVEROUTPUT ON;
SELECT USER FROM dual;
SELECT COUNT(*) AS SO_FARM FROM FARMS;
SELECT COUNT(*) AS SO_TRANSPORT FROM TRANSPORTERS;
SELECT COUNT(*) AS SO_STORE FROM STORES;
SELECT COUNT(*) AS SO_USER FROM USERS;
SELECT COUNT(*) AS SO_LO_HANG FROM PRODUCTS;
SELECT COUNT(*) AS SO_QR FROM QR_CODES;

SELECT PRODUCT_ID, BATCH_CODE, PRODUCT_NAME, STATUS, PICKUP_LOCATION, DELIVERY_LOCATION
FROM PRODUCTS
ORDER BY PRODUCT_ID;

SELECT PRODUCT_ID, TRANSPORT_ID, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE
FROM TRANSPORT_HISTORY
ORDER BY PRODUCT_ID, TRANSPORT_TIME;

SELECT PRODUCT_ID, CERTIFICATE_NAME, STATUS, EXPIRED_DATE
FROM CERTIFICATES
ORDER BY PRODUCT_ID;

SELECT FN_QR_RISK_LEVEL(10, 'NOT_SOLD', 'ACTIVE', 'FRESH') AS SAFE_TEST FROM dual;
SELECT FN_QR_RISK_LEVEL(41, 'NOT_SOLD', 'ACTIVE', 'FRESH') AS WARNING_TEST FROM dual;
SELECT FN_QR_RISK_LEVEL(5, 'SOLD', 'ACTIVE', 'FRESH') AS DANGER_TEST FROM dual;

BEGIN
    PRC_PRINT_OPEN_QR_ALERTS;
END;
/
