/*
  Chạy file này bằng tài khoản SYS/SYSTEM trong SQL Developer nếu chưa có user HONEYBEE.
  Nếu Oracle của bạn dùng XEPDB1 thì đổi FREEPDB1 thành XEPDB1.
*/

ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER HONEYBEE IDENTIFIED BY 12345;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, CREATE SEQUENCE TO HONEYBEE;
ALTER USER HONEYBEE QUOTA UNLIMITED ON USERS;
