/* HoneyBee Trace Oracle - seed demo data doanh nghiep.
   Data dung ASCII de tranh loi ma hoa khi chay SQLPlus/Windows.
   Moc thoi gian demo xoay quanh 2026-06-03.
*/
SET DEFINE OFF;

INSERT INTO FARMS(FARM_ID, FARM_NAME, ADDRESS, OWNER_NAME, CERTIFICATION, CONTACT_PHONE) VALUES (1, 'Da Lat Golden Farm', 'Xuan Tho, Da Lat, Lam Dong', 'Nguyen Minh An', 'VietGAP', '0911000001');
INSERT INTO FARMS(FARM_ID, FARM_NAME, ADDRESS, OWNER_NAME, CERTIFICATION, CONTACT_PHONE) VALUES (2, 'Cai Be Organic Garden', 'Cai Be, Tien Giang', 'Tran Thi Bich', 'GlobalGAP', '0911000002');
INSERT INTO FARMS(FARM_ID, FARM_NAME, ADDRESS, OWNER_NAME, CERTIFICATION, CONTACT_PHONE) VALUES (3, 'Moc Chau Green Farm', 'Moc Chau, Son La', 'Le Quang Huy', 'Organic Demo', '0911000003');

INSERT INTO TRANSPORTERS(TRANSPORTER_ID, TRANSPORTER_NAME, LICENSE_NO, PHONE, TEMPERATURE_SUPPORT) VALUES (1, 'BeeTruck Cold Chain', 'BT-CC-001', '0912000001', '2-15C');
INSERT INTO TRANSPORTERS(TRANSPORTER_ID, TRANSPORTER_NAME, LICENSE_NO, PHONE, TEMPERATURE_SUPPORT) VALUES (2, 'GreenMove Logistics', 'GM-LG-002', '0912000002', 'Ambient/Cold');

INSERT INTO STORES(STORE_ID, STORE_NAME, STORE_TYPE, ADDRESS, CITY, PHONE, CONTACT_PERSON) VALUES (1, 'Honey Mart Quan 1', 'CLEAN_FOOD_STORE', '12 Nguyen Hue, Quan 1, TP.HCM', 'TP.HCM', '0923000001', 'Le Thu Ngan');
INSERT INTO STORES(STORE_ID, STORE_NAME, STORE_TYPE, ADDRESS, CITY, PHONE, CONTACT_PERSON) VALUES (2, 'Green Table Restaurant', 'RESTAURANT', '88 Vo Van Tan, Quan 3, TP.HCM', 'TP.HCM', '0923000002', 'Pham Hoang Anh');

INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (1, 'admin', 'admin123', 'HoneyBee Admin', 'ADMIN', NULL, NULL, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (2, 'farm1', '123456', 'Da Lat Farm Operator', 'FARMER', 1, NULL, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (3, 'transport1', '123456', 'BeeTruck Driver A', 'TRANSPORTER', NULL, 1, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (4, 'store1', '123456', 'Honey Mart Receiver', 'STORE', NULL, NULL, 1);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (5, 'farm2', '123456', 'Cai Be Farm Operator', 'FARMER', 2, NULL, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (6, 'farm3', '123456', 'Moc Chau Farm Operator', 'FARMER', 3, NULL, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (7, 'transport2', '123456', 'GreenMove Driver B', 'TRANSPORTER', NULL, 2, NULL);
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, FULL_NAME, ROLE, FARM_ID, TRANSPORTER_ID, STORE_ID) VALUES (8, 'store2', '123456', 'Green Table Receiver', 'STORE', NULL, NULL, 2);

INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('CREATED','WAITING_FOR_PICKUP','FARMER','Farm confirm batch and handover info');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('WAITING_FOR_PICKUP','IN_TRANSIT','TRANSPORTER','Transport picks up batch');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('IN_TRANSIT','DELIVERED','TRANSPORTER','Transport delivered to store');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('DELIVERED','STORE_RECEIVED','STORE','Store confirms received goods');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('STORE_RECEIVED','AVAILABLE_FOR_SALE','STORE','Store publishes goods for sale');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('DELIVERED','REJECTED','STORE','Store rejects goods');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ROLE_ALLOWED, DESCRIPTION) VALUES ('IN_TRANSIT','RETURN_REQUESTED','TRANSPORTER','Transport reports serious issue');

/* 10 agricultural batches with realistic dates and different business states. */
INSERT INTO PRODUCTS(PRODUCT_ID, FARM_ID, STORE_ID, TRANSPORTER_ID, BATCH_CODE, PRODUCT_NAME, CATEGORY, DESCRIPTION, QUALITY_SUMMARY, PRICE, QUANTITY, UNIT, STATUS, IMAGE_URL, PICKUP_LOCATION, DELIVERY_LOCATION, REQUIRED_TEMP_MIN, REQUIRED_TEMP_MAX, REQUIRED_HUMIDITY_MIN, REQUIRED_HUMIDITY_MAX, TRANSPORT_NOTE, RECEIVER_NAME, RECEIVER_PHONE, EXPECTED_DELIVERY_AT, CREATED_BY) VALUES
(1, 1, 1, 1, 'HB-DL-VEG-001', 'Da Lat Green Mustard Batch 001', 'Leafy Vegetable', 'Fresh green mustard grown in greenhouse A1.', 'Safe cultivation, same-day harvest and cold delivery.', 32000, 120, 'kg', 'AVAILABLE_FOR_SALE', '/assets/veg.svg', 'Da Lat Golden Farm - Cold Room A', 'Honey Mart Quan 1', 6, 10, 70, 90, 'Keep cold 6-10C, keep seal intact.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-02 15:00:00', 2);
INSERT INTO PRODUCTS VALUES (2, 2, 1, 1, 'HB-CB-MANGO-002', 'Cai Be Mango Batch 002', 'Fruit', 'Cat Hoa Loc mango, wrapped and sorted by size.', 'Cold-packed mango, waiting for pickup.', 55000, 80, 'kg', 'WAITING_FOR_PICKUP', 0, '/assets/mango.svg', NULL, NULL, 'Cai Be Organic Garden - Packing Area', 'Honey Mart Quan 1', 10, 15, 65, 85, 'Do not stack over 5 boxes.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-04 10:00:00', 5, TIMESTAMP '2026-06-02 08:00:00', TIMESTAMP '2026-06-02 08:00:00');
INSERT INTO PRODUCTS VALUES (3, 3, 2, 1, 'HB-MC-LETTUCE-003', 'Moc Chau Lettuce Batch 003', 'Leafy Vegetable', 'Lettuce packed in cold bags.', 'In transit with cold-chain monitoring.', 42000, 60, 'kg', 'IN_TRANSIT', 0, '/assets/veg.svg', NULL, NULL, 'Moc Chau Green Farm - Gate 2', 'Green Table Restaurant', 4, 8, 75, 95, 'Priority delivery, check seal at each stop.', 'Pham Hoang Anh', '0923000002', TIMESTAMP '2026-06-03 16:30:00', 6, TIMESTAMP '2026-06-01 07:00:00', TIMESTAMP '2026-06-03 09:00:00');
INSERT INTO PRODUCTS VALUES (4, 1, 1, 2, 'HB-DL-TOMATO-004', 'Da Lat Cherry Tomato Batch 004', 'Fruit Vegetable', 'Cherry tomato boxes for retail.', 'Delivered to store and waiting receiver confirmation.', 48000, 75, 'kg', 'DELIVERED', 0, '/assets/tomato.svg', NULL, NULL, 'Da Lat Golden Farm - Dock B', 'Honey Mart Quan 1', 8, 12, 65, 85, 'Avoid direct sunlight.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-03 13:00:00', 2, TIMESTAMP '2026-06-01 09:00:00', TIMESTAMP '2026-06-03 13:10:00');
INSERT INTO PRODUCTS VALUES (5, 2, 2, 2, 'HB-CB-GUAVA-005', 'Cai Be Guava Batch 005', 'Fruit', 'Crisp guava for restaurant order.', 'Store received but not yet published for sale.', 36000, 90, 'kg', 'STORE_RECEIVED', 0, '/assets/default.svg', NULL, NULL, 'Cai Be Organic Garden - Packing Area', 'Green Table Restaurant', 12, 18, 60, 80, 'Keep dry and ventilated.', 'Pham Hoang Anh', '0923000002', TIMESTAMP '2026-06-03 11:00:00', 5, TIMESTAMP '2026-06-01 10:00:00', TIMESTAMP '2026-06-03 11:30:00');
INSERT INTO PRODUCTS VALUES (6, 3, 1, 1, 'HB-MC-CABBAGE-006', 'Moc Chau Cabbage Batch 006', 'Leafy Vegetable', 'Cabbage batch with temperature issue demo.', 'Transport temperature exceeded max threshold.', 25000, 150, 'kg', 'RETURN_REQUESTED', 0, '/assets/veg.svg', NULL, NULL, 'Moc Chau Green Farm - Gate 1', 'Honey Mart Quan 1', 4, 8, 70, 90, 'Strict cold chain required.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-02 18:00:00', 6, TIMESTAMP '2026-05-31 08:00:00', TIMESTAMP '2026-06-02 18:30:00');
INSERT INTO PRODUCTS VALUES (7, 1, 2, 2, 'HB-DL-CARROT-007', 'Da Lat Carrot Batch 007', 'Root Vegetable', 'Washed carrot in 10kg sacks.', 'Created by farm, not confirmed yet.', 28000, 200, 'kg', 'CREATED', 0, '/assets/default.svg', NULL, NULL, 'Da Lat Golden Farm - Storage C', 'Green Table Restaurant', 8, 15, 60, 85, 'Keep away from moisture.', 'Pham Hoang Anh', '0923000002', TIMESTAMP '2026-06-05 09:00:00', 2, TIMESTAMP '2026-06-03 08:00:00', TIMESTAMP '2026-06-03 08:00:00');
INSERT INTO PRODUCTS VALUES (8, 2, 1, 1, 'HB-CB-DRAGON-008', 'Cai Be Dragon Fruit Batch 008', 'Fruit', 'Red dragon fruit export-grade demo.', 'QR already marked sold to trigger danger warning.', 45000, 110, 'kg', 'AVAILABLE_FOR_SALE', 0, '/assets/default.svg', NULL, NULL, 'Cai Be Organic Garden - Packing Area', 'Honey Mart Quan 1', 10, 18, 60, 80, 'Handle gently, no compression.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-01 15:00:00', 5, TIMESTAMP '2026-05-29 08:00:00', TIMESTAMP '2026-06-01 16:00:00');
INSERT INTO PRODUCTS VALUES (9, 3, 2, 2, 'HB-MC-SPINACH-009', 'Moc Chau Spinach Batch 009', 'Leafy Vegetable', 'Spinach close to expiry demo.', 'Expired freshness status for danger warning.', 30000, 55, 'kg', 'AVAILABLE_FOR_SALE', 0, '/assets/veg.svg', NULL, NULL, 'Moc Chau Green Farm - Dock 3', 'Green Table Restaurant', 4, 8, 75, 95, 'Deliver within 24 hours.', 'Pham Hoang Anh', '0923000002', TIMESTAMP '2026-05-28 09:00:00', 6, TIMESTAMP '2026-05-25 08:00:00', TIMESTAMP '2026-05-28 10:00:00');
INSERT INTO PRODUCTS VALUES (10, 1, 1, 1, 'HB-DL-BASIL-010', 'Da Lat Basil Batch 010', 'Herb', 'Fresh basil leaves for retail pack.', 'Rejected by store because seal was broken.', 60000, 25, 'kg', 'REJECTED', 0, '/assets/default.svg', NULL, NULL, 'Da Lat Golden Farm - Cold Room A', 'Honey Mart Quan 1', 5, 9, 75, 95, 'Fragile herb, check seal carefully.', 'Le Thu Ngan', '0923000001', TIMESTAMP '2026-06-02 12:00:00', 2, TIMESTAMP '2026-05-31 07:00:00', TIMESTAMP '2026-06-02 12:30:00');

INSERT INTO PRODUCT_ORIGIN(PRODUCT_ID, CULTIVATION_PLACE, FARM_ADDRESS, SOWING_DATE, HARVEST_DATE, EXPIRED_DATE, PRODUCTION_PROCESS, FRESHNESS_STATUS) VALUES (1, 'Greenhouse A1, Da Lat', 'Xuan Tho, Da Lat, Lam Dong', DATE '2026-05-01', DATE '2026-06-02', DATE '2026-06-09', 'Seedling, organic care, harvest, cold packing.', 'FRESH');
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 2, 'Mango Area B, Cai Be', 'Cai Be, Tien Giang', DATE '2026-02-20', DATE '2026-06-02', DATE '2026-06-12', 'Fruit bagging, sorting, cold packing.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 3, 'Leafy Area C, Moc Chau', 'Moc Chau, Son La', DATE '2026-05-05', DATE '2026-06-02', DATE '2026-06-06', 'Hydroponic care, cold bagging.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 4, 'Tomato Greenhouse B2, Da Lat', 'Xuan Tho, Da Lat, Lam Dong', DATE '2026-04-10', DATE '2026-06-02', DATE '2026-06-12', 'Controlled greenhouse, color grading.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 5, 'Guava Zone A, Cai Be', 'Cai Be, Tien Giang', DATE '2026-02-01', DATE '2026-06-01', DATE '2026-06-10', 'Fruit bagging and dry packing.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 6, 'Cabbage Field M1, Moc Chau', 'Moc Chau, Son La', DATE '2026-04-20', DATE '2026-06-01', DATE '2026-06-08', 'Field harvest, cold loading.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 7, 'Carrot Field C, Da Lat', 'Xuan Tho, Da Lat, Lam Dong', DATE '2026-04-25', DATE '2026-06-03', DATE '2026-06-20', 'Washed, sorted, sack packed.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 8, 'Dragon Fruit Zone D, Cai Be', 'Cai Be, Tien Giang', DATE '2026-03-12', DATE '2026-05-30', DATE '2026-06-09', 'Fruit grading and retail packing.', 'FRESH', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 9, 'Spinach Hydro Area S, Moc Chau', 'Moc Chau, Son La', DATE '2026-05-01', DATE '2026-05-26', DATE '2026-06-01', 'Hydroponic spinach, cold bagging.', 'EXPIRED', DEFAULT, DEFAULT);
INSERT INTO PRODUCT_ORIGIN VALUES (DEFAULT, 10, 'Herb Greenhouse H1, Da Lat', 'Xuan Tho, Da Lat, Lam Dong', DATE '2026-05-10', DATE '2026-06-01', DATE '2026-06-06', 'Hand harvest, fragile leaf packing.', 'FRESH', DEFAULT, DEFAULT);

INSERT INTO CERTIFICATES(FARM_ID, PRODUCT_ID, CERTIFICATE_NAME, ISSUED_BY, ISSUE_DATE, EXPIRED_DATE, FILE_URL, STATUS) VALUES (1, 1, 'VietGAP Vegetable 2026', 'HoneyBee QC Center', DATE '2026-01-01', DATE '2026-12-31', 'docs/cert-vietgap-dalat.pdf', 'VALID');
INSERT INTO CERTIFICATES VALUES (DEFAULT, 2, 2, 'GlobalGAP Mango 2026', 'HoneyBee QC Center', DATE '2026-01-15', DATE '2026-12-31', 'docs/cert-mango.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 3, 3, 'Organic Leafy Demo', 'HoneyBee QC Center', DATE '2026-02-01', DATE '2026-11-30', 'docs/cert-lettuce.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 1, 4, 'VietGAP Tomato 2026', 'HoneyBee QC Center', DATE '2026-01-01', DATE '2026-12-31', 'docs/cert-tomato.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 2, 5, 'Fruit Safety 2026', 'HoneyBee QC Center', DATE '2026-01-10', DATE '2026-12-31', 'docs/cert-guava.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 3, 6, 'Cold Chain Vegetable Cert', 'HoneyBee QC Center', DATE '2026-02-01', DATE '2026-12-31', 'docs/cert-cabbage.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 1, 7, 'Root Vegetable Cert 2026', 'HoneyBee QC Center', DATE '2026-01-01', DATE '2026-12-31', 'docs/cert-carrot.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 2, 8, 'Fruit Safety 2026', 'HoneyBee QC Center', DATE '2026-01-10', DATE '2026-12-31', 'docs/cert-dragon.pdf', 'VALID', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 3, 9, 'Leafy Vegetable Cert Expired', 'HoneyBee QC Center', DATE '2025-01-01', DATE '2026-05-31', 'docs/cert-spinach-expired.pdf', 'EXPIRED', DEFAULT);
INSERT INTO CERTIFICATES VALUES (DEFAULT, 1, 10, 'Herb Safety Cert 2026', 'HoneyBee QC Center', DATE '2026-01-01', DATE '2026-12-31', 'docs/cert-basil.pdf', 'VALID', DEFAULT);

INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (1, 1, 'BeeTruck Cold Chain', 'Da Lat Golden Farm - Cold Room A', 'Honey Mart Quan 1', 'Honey Mart Quan 1', TIMESTAMP '2026-06-02 14:30:00', 8.0, 80, 'INTACT', 'DELIVERED', 'Delivered successfully.', NULL, 3);
INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (3, 1, 'BeeTruck Cold Chain', 'Moc Chau Green Farm - Gate 2', 'Lam Dong Hub', 'Lam Dong Hub', TIMESTAMP '2026-06-03 09:30:00', 6.5, 82, 'INTACT', 'ARRIVED_AT_HUB', 'Arrived hub, cold chain normal.', NULL, 3);
INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (4, 2, 'GreenMove Logistics', 'Da Lat Golden Farm - Dock B', 'Honey Mart Quan 1', 'Honey Mart Quan 1', TIMESTAMP '2026-06-03 13:00:00', 10.0, 74, 'INTACT', 'DELIVERED', 'Waiting store receiver.', NULL, 7);
INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (5, 2, 'GreenMove Logistics', 'Cai Be Organic Garden - Packing Area', 'Green Table Restaurant', 'Green Table Restaurant', TIMESTAMP '2026-06-03 11:00:00', 15.0, 72, 'INTACT', 'DELIVERED', 'Store received.', NULL, 7);
INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (6, 1, 'BeeTruck Cold Chain', 'Moc Chau Green Farm - Gate 1', 'Honey Mart Quan 1', 'Bao Loc Checkpoint', TIMESTAMP '2026-06-02 15:45:00', 14.5, 92, 'INTACT', 'RETURN_REQUESTED', 'Temperature exceeded threshold, return requested.', 'Temperature exceeded required range.', 3);
INSERT INTO TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORTER_ID, TRANSPORT_COMPANY, FROM_LOCATION, TO_LOCATION, CURRENT_LOCATION, TRANSPORT_TIME, STORAGE_TEMPERATURE, HUMIDITY, SEAL_STATUS, STATUS, NOTE, ISSUE_NOTE, CREATED_BY) VALUES (10, 1, 'BeeTruck Cold Chain', 'Da Lat Golden Farm - Cold Room A', 'Honey Mart Quan 1', 'Honey Mart Quan 1', TIMESTAMP '2026-06-02 12:10:00', 7.5, 78, 'BROKEN', 'REJECTED', 'Store rejected because seal broken.', 'Broken seal.', 3);

INSERT INTO DISTRIBUTION_HISTORY(PRODUCT_ID, STORE_ID, RECEIVED_AT, RECEIVED_BY, QUANTITY_RECEIVED, STATUS, NOTE, REJECT_REASON) VALUES (1, 1, TIMESTAMP '2026-06-02 15:05:00', 4, 120, 'AVAILABLE_FOR_SALE', 'Goods checked and published for sale.', NULL);
INSERT INTO DISTRIBUTION_HISTORY(PRODUCT_ID, STORE_ID, RECEIVED_AT, RECEIVED_BY, QUANTITY_RECEIVED, STATUS, NOTE, REJECT_REASON) VALUES (5, 2, TIMESTAMP '2026-06-03 11:20:00', 8, 90, 'STORE_RECEIVED', 'Received, waiting kitchen QC.', NULL);
INSERT INTO DISTRIBUTION_HISTORY(PRODUCT_ID, STORE_ID, RECEIVED_AT, RECEIVED_BY, QUANTITY_RECEIVED, STATUS, NOTE, REJECT_REASON) VALUES (8, 1, TIMESTAMP '2026-06-01 16:20:00', 4, 110, 'AVAILABLE_FOR_SALE', 'Goods published for sale.', NULL);
INSERT INTO DISTRIBUTION_HISTORY(PRODUCT_ID, STORE_ID, RECEIVED_AT, RECEIVED_BY, QUANTITY_RECEIVED, STATUS, NOTE, REJECT_REASON) VALUES (9, 2, TIMESTAMP '2026-05-28 10:10:00', 8, 55, 'AVAILABLE_FOR_SALE', 'Old stock sample for expired demo.', NULL);
INSERT INTO DISTRIBUTION_HISTORY(PRODUCT_ID, STORE_ID, RECEIVED_AT, RECEIVED_BY, QUANTITY_RECEIVED, STATUS, NOTE, REJECT_REASON) VALUES (10, 1, TIMESTAMP '2026-06-02 12:25:00', 4, 0, 'REJECTED', 'Rejected because seal was broken.', 'Broken seal');

INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (1, NULL, 'CREATED', 2, TIMESTAMP '2026-06-02 06:00:00', 'Farm created batch.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (1, 'CREATED', 'WAITING_FOR_PICKUP', 2, TIMESTAMP '2026-06-02 08:00:00', 'Farm confirmed handover.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (1, 'WAITING_FOR_PICKUP', 'IN_TRANSIT', 3, TIMESTAMP '2026-06-02 10:00:00', 'Transport picked up.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (1, 'IN_TRANSIT', 'DELIVERED', 3, TIMESTAMP '2026-06-02 14:30:00', 'Delivered.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (1, 'DELIVERED', 'AVAILABLE_FOR_SALE', 4, TIMESTAMP '2026-06-02 15:05:00', 'Store published for sale.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (2, NULL, 'WAITING_FOR_PICKUP', 5, TIMESTAMP '2026-06-02 08:00:00', 'Farm confirmed waiting pickup.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (3, NULL, 'IN_TRANSIT', 6, TIMESTAMP '2026-06-03 09:00:00', 'Transport in progress.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (6, 'IN_TRANSIT', 'RETURN_REQUESTED', 3, TIMESTAMP '2026-06-02 16:00:00', 'Temperature issue.');
INSERT INTO BATCH_STATUS_HISTORY(PRODUCT_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT, NOTE) VALUES (10, 'DELIVERED', 'REJECTED', 4, TIMESTAMP '2026-06-02 12:30:00', 'Store rejected due to broken seal.');

INSERT INTO PRODUCT_UPDATES(PRODUCT_ID, UPDATE_TITLE, UPDATE_CONTENT, UPDATED_BY, UPDATED_AT) VALUES (1, 'Harvest', 'Harvested and cold packed at Da Lat farm.', 'farm1', TIMESTAMP '2026-06-02 06:30:00');
INSERT INTO PRODUCT_UPDATES VALUES (DEFAULT, 3, 'Transport checkpoint', 'Reached Lam Dong hub, seal intact.', 'transport1', TIMESTAMP '2026-06-03 09:30:00');
INSERT INTO PRODUCT_UPDATES VALUES (DEFAULT, 6, 'Temperature issue', 'Storage temperature exceeded max threshold.', 'transport1', TIMESTAMP '2026-06-02 15:45:00');
INSERT INTO PRODUCT_UPDATES VALUES (DEFAULT, 10, 'Store rejection', 'Store rejected because seal was broken.', 'store1', TIMESTAMP '2026-06-02 12:30:00');

INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS, SOLD_AT, SOLD_NOTE) VALUES (1, 'HB-QR-VEG-001-SAFE', 'DEMO_SIGNATURE_SAFE', 'http://localhost:8080/product-detail.html?token=HB-QR-VEG-001-SAFE&sig=DEMO_SIGNATURE_SAFE', 'http://localhost:8080/api/qr/product/1/image', 'ACTIVE', 'NOT_SOLD', NULL, NULL);
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (2, 'HB-QR-MANGO-002-WARN40', 'DEMO_SIGNATURE_WARN40', 'http://localhost:8080/product-detail.html?token=HB-QR-MANGO-002-WARN40&sig=DEMO_SIGNATURE_WARN40', 'http://localhost:8080/api/qr/product/2/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (3, 'HB-QR-LETTUCE-003-TRANSIT', 'DEMO_SIGNATURE_TRANSIT', 'http://localhost:8080/product-detail.html?token=HB-QR-LETTUCE-003-TRANSIT&sig=DEMO_SIGNATURE_TRANSIT', 'http://localhost:8080/api/qr/product/3/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (4, 'HB-QR-TOMATO-004-DELIVERED', 'DEMO_SIGNATURE_DELIVERED', 'http://localhost:8080/product-detail.html?token=HB-QR-TOMATO-004-DELIVERED&sig=DEMO_SIGNATURE_DELIVERED', 'http://localhost:8080/api/qr/product/4/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (5, 'HB-QR-GUAVA-005-STORE', 'DEMO_SIGNATURE_STORE', 'http://localhost:8080/product-detail.html?token=HB-QR-GUAVA-005-STORE&sig=DEMO_SIGNATURE_STORE', 'http://localhost:8080/api/qr/product/5/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (6, 'HB-QR-CABBAGE-006-TEMP', 'DEMO_SIGNATURE_TEMP', 'http://localhost:8080/product-detail.html?token=HB-QR-CABBAGE-006-TEMP&sig=DEMO_SIGNATURE_TEMP', 'http://localhost:8080/api/qr/product/6/image', 'SUSPICIOUS', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (7, 'HB-QR-CARROT-007-CREATED', 'DEMO_SIGNATURE_CREATED', 'http://localhost:8080/product-detail.html?token=HB-QR-CARROT-007-CREATED&sig=DEMO_SIGNATURE_CREATED', 'http://localhost:8080/api/qr/product/7/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS, SOLD_AT, SOLD_NOTE) VALUES (8, 'HB-QR-DRAGON-008-SOLD', 'DEMO_SIGNATURE_SOLD', 'http://localhost:8080/product-detail.html?token=HB-QR-DRAGON-008-SOLD&sig=DEMO_SIGNATURE_SOLD', 'http://localhost:8080/api/qr/product/8/image', 'ACTIVE', 'SOLD', TIMESTAMP '2026-06-02 18:00:00', 'Sold at POS demo. New scan should be DANGER if label appears again.');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (9, 'HB-QR-SPINACH-009-EXPIRED', 'DEMO_SIGNATURE_EXPIRED', 'http://localhost:8080/product-detail.html?token=HB-QR-SPINACH-009-EXPIRED&sig=DEMO_SIGNATURE_EXPIRED', 'http://localhost:8080/api/qr/product/9/image', 'ACTIVE', 'NOT_SOLD');
INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, QR_IMAGE_URL, STATUS, SALE_STATUS) VALUES (10, 'HB-QR-BASIL-010-BROKENSEAL', 'DEMO_SIGNATURE_BROKEN', 'http://localhost:8080/product-detail.html?token=HB-QR-BASIL-010-BROKENSEAL&sig=DEMO_SIGNATURE_BROKEN', 'http://localhost:8080/api/qr/product/10/image', 'SUSPICIOUS', 'NOT_SOLD');

/* Scan data: product 1 safe, product 2 has 41 scans today => WARNING, product 8/9/10 demonstrate DANGER conditions. */
BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO QR_SCAN_LOGS(QR_TOKEN, PRODUCT_ID, IP_ADDRESS, USER_AGENT, RESULT_STATUS, WARNING_LEVEL, WARNING_MESSAGE, SCANNED_AT)
    VALUES ('HB-QR-VEG-001-SAFE', 1, '127.0.0.'||i, 'Seed Browser', 'SUCCESS', 'NONE', 'Safe scan demo.', CURRENT_TIMESTAMP - NUMTODSINTERVAL(i, 'MINUTE'));
  END LOOP;
  FOR i IN 1..41 LOOP
    INSERT INTO QR_SCAN_LOGS(QR_TOKEN, PRODUCT_ID, IP_ADDRESS, USER_AGENT, RESULT_STATUS, WARNING_LEVEL, WARNING_MESSAGE, SCANNED_AT)
    VALUES ('HB-QR-MANGO-002-WARN40', 2, '10.0.0.'||i, 'Seed Browser', 'SUCCESS', CASE WHEN i <= 40 THEN 'NONE' ELSE 'MEDIUM' END, 'Seed scans for >40 warning demo.', CURRENT_TIMESTAMP - NUMTODSINTERVAL(i, 'MINUTE'));
  END LOOP;
END;
/

INSERT INTO QR_SECURITY_ALERTS(QR_TOKEN, PRODUCT_ID, ALERT_TYPE, ALERT_LEVEL, ALERT_MESSAGE) VALUES ('HB-QR-CABBAGE-006-TEMP', 6, 'COLD_CHAIN_TEMP', 'HIGH', 'Storage temperature exceeded required range during transport.');
INSERT INTO QR_SECURITY_ALERTS(QR_TOKEN, PRODUCT_ID, ALERT_TYPE, ALERT_LEVEL, ALERT_MESSAGE) VALUES ('HB-QR-DRAGON-008-SOLD', 8, 'SOLD_QR_RESCAN', 'HIGH', 'QR already sold; later scans can indicate copied label.');
INSERT INTO QR_SECURITY_ALERTS(QR_TOKEN, PRODUCT_ID, ALERT_TYPE, ALERT_LEVEL, ALERT_MESSAGE) VALUES ('HB-QR-SPINACH-009-EXPIRED', 9, 'EXPIRED_PRODUCT', 'HIGH', 'Product freshness status is expired.');
INSERT INTO QR_SECURITY_ALERTS(QR_TOKEN, PRODUCT_ID, ALERT_TYPE, ALERT_LEVEL, ALERT_MESSAGE) VALUES ('HB-QR-BASIL-010-BROKENSEAL', 10, 'BROKEN_SEAL', 'HIGH', 'Store rejected because seal was broken.');

INSERT INTO AUDIT_LOGS(TABLE_NAME, RECORD_ID, ACTION_TYPE, NEW_DATA, PERFORMED_BY) VALUES ('PRODUCTS', '1-10', 'SEED', 'Inserted 10 demo agricultural batches.', 'system');
INSERT INTO AUDIT_LOGS(TABLE_NAME, RECORD_ID, ACTION_TYPE, NEW_DATA, PERFORMED_BY) VALUES ('QR_SCAN_LOGS', 'HB-QR-MANGO-002-WARN40', 'SEED', 'Inserted 41 scans for warning threshold demo.', 'system');

COMMIT;
