SET DEFINE OFF;
SET SERVEROUTPUT ON;
PROMPT === HoneyBee Web Oracle schema health check ===
SELECT USER AS CURRENT_SCHEMA FROM dual;

PROMPT === Required tables ===
SELECT table_name
FROM user_tables
WHERE table_name IN (
 'FARMS','TRANSPORTERS','STORES','USERS','PRODUCTS','PRODUCT_ORIGIN','CERTIFICATES',
 'TRANSPORT_HISTORY','DISTRIBUTION_HISTORY','BATCH_STATUS_HISTORY','PRODUCT_UPDATES',
 'QR_CODES','QR_SCAN_LOGS','QR_SECURITY_ALERTS','AUDIT_LOGS','APP_SCHEMA_INFO'
)
ORDER BY table_name;

PROMPT === Required PRODUCTS columns ===
SELECT column_name
FROM user_tab_columns
WHERE table_name = 'PRODUCTS'
  AND column_name IN (
    'PRODUCT_ID','FARM_ID','STORE_ID','TRANSPORTER_ID','BATCH_CODE','PRODUCT_NAME','CATEGORY',
    'DESCRIPTION','QUALITY_SUMMARY','PRICE','QUANTITY','UNIT','STATUS','VERSION_NO','IMAGE_URL','PRODUCT_IMAGE_B64','PRODUCT_IMAGE_MIME',
    'PICKUP_LOCATION','DELIVERY_LOCATION','REQUIRED_TEMP_MIN','REQUIRED_TEMP_MAX',
    'REQUIRED_HUMIDITY_MIN','REQUIRED_HUMIDITY_MAX','TRANSPORT_NOTE','RECEIVER_NAME',
    'RECEIVER_PHONE','EXPECTED_DELIVERY_AT','CREATED_BY','CREATED_AT','UPDATED_AT'
  )
ORDER BY column_id;

PROMPT === Seed counts ===
SELECT COUNT(*) AS FARMS FROM FARMS;
SELECT COUNT(*) AS TRANSPORTERS FROM TRANSPORTERS;
SELECT COUNT(*) AS STORES FROM STORES;
SELECT COUNT(*) AS USERS FROM USERS;
SELECT COUNT(*) AS PRODUCTS FROM PRODUCTS;
SELECT COUNT(*) AS QR_CODES FROM QR_CODES;

PROMPT === Demo login users ===
SELECT username, role, farm_id, transporter_id, store_id, status
FROM users
ORDER BY user_id;

PROMPT === Demo products ===
SELECT product_id, batch_code, product_name, status, store_id, transporter_id, pickup_location, delivery_location
FROM products
ORDER BY product_id;
