const loadingEl = document.getElementById('loading');
const contentEl = document.getElementById('content');
function trustClass(level){ return level==='SAFE'?'safe':(level==='WARNING'?'warning':'danger'); }
function trustIcon(level){ return level==='SAFE'?'✅':(level==='WARNING'?'⚠️':'🚨'); }
function certBadge(status){ const s=String(status||'UNKNOWN'); const cls=s==='VALID'?'safe':(['EXPIRED','REVOKED'].includes(s)?'danger':'warning'); return `<span class="hb-badge ${cls}">🏅 ${escapeHtml(s)}</span>`; }
function renderKv(label,value){ return `<div><span>${label}</span><span>${escapeHtml(value ?? 'Chưa có')}</span></div>`; }
function renderTrace(data){
  const info=data.info||{}, trust=data.trustStatus||{level:'UNKNOWN',title:'Không xác định',message:'Không có dữ liệu'}, rec=data.recommendation||{};
  const certificates=data.certificates||[], journey=data.journey||[], alerts=data.securityAlerts||[], transports=data.transports||[], statusHistory=data.statusHistory||[], distributions=data.distributions||[];
  contentEl.innerHTML=`
  <section class="hb-card hb-trust ${trustClass(trust.level)}"><span class="hb-badge ${trustClass(trust.level)}">${trustIcon(trust.level)} ${escapeHtml(trust.level)}</span><h2>${escapeHtml(trust.title)}</h2><p>${escapeHtml(trust.message)}</p><div class="hb-kv">${renderKv('Lượt quét hôm nay',trust.todayScanCount??0)}${renderKv('Tổng lượt quét',trust.totalScanCount??0)}${renderKv('Trạng thái bán QR',trust.qrSaleStatus||info.QR_SALE_STATUS||'NOT_SOLD')}${renderKv('Thời điểm bán',fmtDate(trust.soldAt||info.SOLD_AT))}${renderKv('Khuyến nghị',rec.message||'Chưa có')}</div></section>
  <section class="hb-card"><div style="display:flex;gap:14px;align-items:center"><img src="${escapeHtml(productImageSrc(info))}" style="width:82px;height:82px;border-radius:20px;background:#fff3c4;padding:10px" onerror="this.src='assets/default.svg'"><div><span class="hb-badge">📦 ${escapeHtml(info.BATCH_CODE||'Lô sản phẩm')}</span><h2>${escapeHtml(info.PRODUCT_NAME||'Không có tên')}</h2><p>${escapeHtml(info.DESCRIPTION||'')}</p></div></div><div class="hb-kv">${renderKv('Trạng thái lô',info.PRODUCT_STATUS)}${renderKv('Số lượng',`${info.QUANTITY??''} ${info.UNIT??''}`)}${renderKv('Nông trại',info.FARM_NAME)}${renderKv('Nơi trồng',info.CULTIVATION_PLACE)}${renderKv('Quy trình',info.PRODUCTION_PROCESS)}${renderKv('Ngày thu hoạch',fmtDate(info.HARVEST_DATE))}${renderKv('Hạn sử dụng',fmtDate(info.EXPIRED_DATE))}${renderKv('Độ tươi',info.FRESHNESS_STATUS)}${renderKv('Store nhận',info.STORE_NAME)}${renderKv('Điểm lấy',info.PICKUP_LOCATION)}${renderKv('Điểm giao',info.DELIVERY_LOCATION)}${renderKv('Yêu cầu nhiệt độ',`${info.REQUIRED_TEMP_MIN??'?'}-${info.REQUIRED_TEMP_MAX??'?'}°C`)}${renderKv('Yêu cầu độ ẩm',`${info.REQUIRED_HUMIDITY_MIN??'?'}-${info.REQUIRED_HUMIDITY_MAX??'?'}%`)}</div></section>
  <section class="hb-card"><h3>🐝 Hành trình sản phẩm</h3><div class="hb-timeline">${journey.length?journey.map(j=>`<div class="hb-step"><div class="hb-step-icon">${escapeHtml(j.icon||'•')}</div><div><h4>${escapeHtml(j.title)}</h4><p>${escapeHtml(j.description)}</p><time>${fmtDate(j.time)}</time></div></div>`).join(''):'<p>Chưa có dữ liệu hành trình.</p>'}</div></section>
  <section class="hb-card"><h3>🚚 Lịch sử vận chuyển chi tiết</h3>${transports.length?transports.map(t=>`<div class="hb-item"><div><b>${escapeHtml(t.STATUS)}</b><p>${escapeHtml(t.FROM_LOCATION||'')} → ${escapeHtml(t.TO_LOCATION||'')}</p><p>Vị trí: ${escapeHtml(t.CURRENT_LOCATION||'')} | ${t.STORAGE_TEMPERATURE??''}°C | ${t.HUMIDITY??''}% | Seal: ${escapeHtml(t.SEAL_STATUS||'')}</p><p>${fmtDate(t.TRANSPORT_TIME)} - ${escapeHtml(t.NOTE||t.ISSUE_NOTE||'')}</p></div></div>`).join(''):'<p>Chưa có chặng vận chuyển.</p>'}</section>
  <section class="hb-card"><h3>🏪 Store/Phân phối</h3>${distributions.length?distributions.map(d=>`<div class="hb-item"><div><b>${escapeHtml(d.STORE_NAME||'Store')} - ${escapeHtml(d.STATUS)}</b><p>${fmtDate(d.RECEIVED_AT)} | SL nhận: ${d.QUANTITY_RECEIVED??'Chưa nhập'}</p><p>${escapeHtml(d.NOTE||d.REJECT_REASON||'')}</p></div></div>`).join(''):'<p>Store chưa xác nhận nhận hàng.</p>'}</section>
  <section class="hb-card"><h3>🏅 Chứng chỉ</h3>${certificates.length?certificates.map(c=>`<div style="padding:12px 0;border-bottom:1px dashed var(--hb-border)">${certBadge(c.STATUS)}<strong style="display:block;margin-top:8px">${escapeHtml(c.CERTIFICATE_NAME)}</strong><small>${escapeHtml(c.ISSUED_BY||'')} · Ngày cấp: ${fmtDate(c.ISSUE_DATE)} · Hết hạn: ${fmtDate(c.EXPIRED_DATE)}</small><p>${c.FILE_URL?`<a href="${escapeHtml(c.FILE_URL)}">Xem file/link chứng chỉ</a>`:''}</p></div>`).join(''):'<p>Lô hàng chưa có chứng chỉ an toàn thực phẩm được công khai.</p>'}</section>
  <section class="hb-card"><h3>📜 Lịch sử trạng thái</h3>${statusHistory.length?statusHistory.map(s=>`<p><b>${escapeHtml(s.OLD_STATUS||'START')} → ${escapeHtml(s.NEW_STATUS)}</b> · ${fmtDate(s.CHANGED_AT)}<br>${escapeHtml(s.NOTE||'')}</p>`).join(''):'<p>Chưa có lịch sử trạng thái.</p>'}</section>
  <section class="hb-card"><h3>🛡️ Cảnh báo</h3>${alerts.length?alerts.map(a=>`<p><span class="hb-badge ${a.ALERT_LEVEL==='HIGH'||a.ALERT_LEVEL==='CRITICAL'?'danger':'warning'}">${escapeHtml(a.ALERT_LEVEL)}</span> ${escapeHtml(a.ALERT_MESSAGE)}</p>`).join(''):'<p>Không có cảnh báo bảo mật đang mở.</p>'}<p style="color:var(--hb-muted);font-size:.92rem">Quy tắc scan: 0-40 lượt/ngày là SAFE nếu không có rủi ro khác; >40 lượt là WARNING; DANGER khi QR/lô đã bán, hết hạn, thu hồi, sai chữ ký hoặc có sự cố nghiêm trọng.</p></section>`;
}
async function init(){ try{ const token=getParam('token'), sig=getParam('sig'), id=getParam('id'); let data; if(token){data=await apiGet(`/trace/token/${encodeURIComponent(token)}${sig?`?sig=${encodeURIComponent(sig)}`:''}`);} else if(id){data=await apiGet(`/trace/product/${encodeURIComponent(id)}`);} else throw new Error('Thiếu token QR hoặc id sản phẩm.'); renderTrace(data);} catch(err){ contentEl.innerHTML=`<section class="hb-card hb-trust danger"><span class="hb-badge danger">❌ ERROR</span><h2>Không thể xác thực</h2><p>${escapeHtml(err.message)}</p><a class="hb-btn" href="scanner.html">Quét lại</a></section>`;} finally{ loadingEl.style.display='none'; contentEl.style.display='block'; }}
init();
